DROP DATABASE IF EXISTS loginDB;
CREATE DATABASE loginDB;

/* CREATE TABLE */

USE loginDB;
CREATE TABLE users(
id INTEGER NOT NULL AUTO_INCREMENT, 
email VARCHAR(100),
password VARCHAR(100),
name VARCHAR(100),
PRIMARY KEY (id)
);
    
USE loginDB;
SELECT * FROM users;